<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUHF2riU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUHF2riU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUHF2riU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUHF2riU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUHF2riU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UHF2riU',
    'container.build_id' => '3bdfb978',
    'container.build_time' => 1733826663,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUHF2riU');
