<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlGr6mY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlGr6mY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPlGr6mY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPlGr6mY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPlGr6mY\App_KernelDevDebugContainer([
    'container.build_hash' => 'PlGr6mY',
    'container.build_id' => '6d44adba',
    'container.build_time' => 1733932409,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlGr6mY');
